/**
 * agents/src/hooks/audit-logger.ts
 *
 * The audit event type contract and the AuditLogger interface — the shared
 * vocabulary for everything that writes to the audit trail.
 *
 * The `AuditEvent` interface mirrors the Rust `AuditEvent` struct in
 * src-tauri/src/audit/schema.rs and is kept in sync manually; both serialize
 * to the same camelCase JSON at the IPC boundary. The Rust audit store does
 * not generate `id` or `timestamp` — the TypeScript layer supplies a complete
 * event — so those fields are part of this contract.
 *
 * The PostToolUse hook that automatically emits "tool.invoked"/"tool.completed"
 * events, and the concrete AuditLogger implementation that transports events
 * to the Rust store over Tauri IPC, are implemented in issue #10. This module
 * currently defines only the types and the logger contract that the
 * scope-enforcement hook (issue #7) and the rest of the agent layer depend on.
 *
 * See docs/architecture/sdlc-agent-architecture-research-v4.md Section 8
 * for the audit trail design and Section 8.2 for the event schema.
 */

/**
 * Exhaustive set of audit event types, as dot-notation strings. Mirrors the
 * `AuditEventType` enum in src-tauri/src/audit/schema.rs.
 *
 * Categories: lifecycle (agent.*), actions (tool.*, file.*, issue.*, memory.*),
 * decisions (decision.*, handoff.*), and security (scope.violation,
 * credential.expired, auth.failed).
 */
export type AuditEventType =
  // Lifecycle events
  | 'agent.created'
  | 'agent.completed'
  | 'agent.failed'
  | 'agent.expired'
  // Action events
  | 'tool.invoked'
  | 'tool.completed'
  | 'tool.blocked'
  | 'file.read'
  | 'file.write'
  | 'file.delete'
  | 'issue.created'
  | 'issue.updated'
  | 'issue.closed'
  | 'memory.read'
  | 'memory.write'
  // Decision events
  | 'decision.routing'
  | 'decision.approval'
  | 'decision.rejection'
  | 'handoff.initiated'
  | 'handoff.completed'
  // Security events
  | 'scope.violation'
  | 'credential.expired'
  | 'auth.failed';

/** Outcome of an audited action. Mirrors `AuditResult` in schema.rs. */
export type AuditResult = 'success' | 'failure' | 'blocked' | 'pending';

/**
 * A single audit event capturing an agent action, decision, or lifecycle
 * transition. The audit trail is append-only — events are never modified or
 * deleted once written.
 *
 * Field names are camelCase to match the JSON the Rust audit store reads and
 * writes (see schema.rs `#[serde(rename_all = "camelCase")]`).
 */
export interface AuditEvent {
  /** Unique event identifier (UUID v4), generated by the producer. */
  readonly id: string;
  /** ISO 8601 timestamp of when the event occurred. */
  readonly timestamp: string;
  /** Project this event belongs to. */
  readonly projectId: string;
  /** Identity id of the agent that performed the action. */
  readonly agentId: string;
  /** Role of the agent, e.g. "code-agent". */
  readonly agentRole: string;
  /** Full delegation chain from this agent back to the human. */
  readonly delegationChain: readonly string[];
  /** Type of event — categorizes what happened. */
  readonly eventType: AuditEventType;
  /** Human-readable description of the action. */
  readonly action: string;
  /** Structured details — tool parameters, file paths, metadata. */
  readonly details: Record<string, unknown>;
  /** Issue-tracker reference, e.g. "PROJ-167". Omitted when not applicable. */
  readonly issueRef?: string;
  /** Initiative reference, e.g. "PROJ-100". Omitted when not applicable. */
  readonly initiativeRef?: string;
  /** Claude SDK session id, for grouping events from the same session. */
  readonly sessionId: string;
  /** Outcome of the action. */
  readonly result: AuditResult;
  /** Explanation, especially for blocked or failed actions. Omitted when none. */
  readonly reason?: string;
}

/**
 * The contract for anything that writes to the audit trail. Hooks depend on
 * this interface rather than a concrete store so that the transport (Tauri IPC
 * to the Rust audit store) can be swapped without touching hook logic, and so
 * that tests can inject a recording double.
 *
 * The concrete IPC-backed implementation is provided in issue #10.
 */
export interface AuditLogger {
  /** Append a fully-formed event to the audit trail. */
  log(event: AuditEvent): Promise<void>;
}
